// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "./date_pb";
import type { ReadingStatus } from "./reading_status_pb";

/**
 * Describes the file readly/v1/book.proto.
 */
export declare const file_readly_v1_book: GenFile;

/**
 * @generated from message readly.v1.Book
 */
export declare type Book = Message<"readly.v1.Book"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated string genres = 3;
   */
  genres: string[];

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string cover_image_url = 5;
   */
  coverImageUrl?: string;

  /**
   * @generated from field: optional string url = 6;
   */
  url?: string;

  /**
   * @generated from field: optional string author_name = 7;
   */
  authorName?: string;

  /**
   * @generated from field: optional string publisher_name = 8;
   */
  publisherName?: string;

  /**
   * @generated from field: optional readly.v1.Date publish_date = 9;
   */
  publishDate?: Date;

  /**
   * @generated from field: optional string isbn = 10;
   */
  isbn?: string;

  /**
   * @generated from field: readly.v1.ReadingStatus reading_status = 11;
   */
  readingStatus: ReadingStatus;

  /**
   * @generated from field: optional readly.v1.Date start_date = 12;
   */
  startDate?: Date;

  /**
   * @generated from field: optional readly.v1.Date end_date = 13;
   */
  endDate?: Date;
};

/**
 * Describes the message readly.v1.Book.
 * Use `create(BookSchema)` to create a new message.
 */
export declare const BookSchema: GenMessage<Book>;

