// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_readly_v1_date } from "./date_pb";
import { file_readly_v1_reading_status } from "./reading_status_pb";

/**
 * Describes the file readly/v1/book.proto.
 */
export const file_readly_v1_book = /*@__PURE__*/
  fileDesc("ChRyZWFkbHkvdjEvYm9vay5wcm90bxIJcmVhZGx5LnYxIvoDCgRCb29rEgoKAmlkGAEgASgDEg0KBXRpdGxlGAIgASgJEg4KBmdlbnJlcxgDIAMoCRIYCgtkZXNjcmlwdGlvbhgEIAEoCUgAiAEBEhwKD2NvdmVyX2ltYWdlX3VybBgFIAEoCUgBiAEBEhAKA3VybBgGIAEoCUgCiAEBEhgKC2F1dGhvcl9uYW1lGAcgASgJSAOIAQESGwoOcHVibGlzaGVyX25hbWUYCCABKAlIBIgBARIqCgxwdWJsaXNoX2RhdGUYCSABKAsyDy5yZWFkbHkudjEuRGF0ZUgFiAEBEhEKBGlzYm4YCiABKAlIBogBARIwCg5yZWFkaW5nX3N0YXR1cxgLIAEoDjIYLnJlYWRseS52MS5SZWFkaW5nU3RhdHVzEigKCnN0YXJ0X2RhdGUYDCABKAsyDy5yZWFkbHkudjEuRGF0ZUgHiAEBEiYKCGVuZF9kYXRlGA0gASgLMg8ucmVhZGx5LnYxLkRhdGVICIgBAUIOCgxfZGVzY3JpcHRpb25CEgoQX2NvdmVyX2ltYWdlX3VybEIGCgRfdXJsQg4KDF9hdXRob3JfbmFtZUIRCg9fcHVibGlzaGVyX25hbWVCDwoNX3B1Ymxpc2hfZGF0ZUIHCgVfaXNibkINCgtfc3RhcnRfZGF0ZUILCglfZW5kX2RhdGVCdwoNY29tLnJlYWRseS52MUIJQm9va1Byb3RvUAFaFnJlYWRseS9wYi9yZWFkbHkvdjE7cGKiAgNSWFiqAglSZWFkbHkuVjHKAglSZWFkbHlcVjHiAhVSZWFkbHlcVjFcR1BCTWV0YWRhdGHqAgpSZWFkbHk6OlYxYgZwcm90bzM", [file_readly_v1_date, file_readly_v1_reading_status]);

/**
 * Describes the message readly.v1.Book.
 * Use `create(BookSchema)` to create a new message.
 */
export const BookSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_book, 0);

