// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/date.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file readly/v1/date.proto.
 */
export declare const file_readly_v1_date: GenFile;

/**
 * @generated from message readly.v1.Date
 */
export declare type Date = Message<"readly.v1.Date"> & {
  /**
   * @generated from field: int32 year = 1;
   */
  year: number;

  /**
   * @generated from field: int32 month = 2;
   */
  month: number;

  /**
   * @generated from field: int32 day = 3;
   */
  day: number;
};

/**
 * Describes the message readly.v1.Date.
 * Use `create(DateSchema)` to create a new message.
 */
export declare const DateSchema: GenMessage<Date>;

