// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/date.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file readly/v1/date.proto.
 */
export const file_readly_v1_date = /*@__PURE__*/
  fileDesc("ChRyZWFkbHkvdjEvZGF0ZS5wcm90bxIJcmVhZGx5LnYxIjAKBERhdGUSDAoEeWVhchgBIAEoBRINCgVtb250aBgCIAEoBRILCgNkYXkYAyABKAVCdwoNY29tLnJlYWRseS52MUIJRGF0ZVByb3RvUAFaFnJlYWRseS9wYi9yZWFkbHkvdjE7cGKiAgNSWFiqAglSZWFkbHkuVjHKAglSZWFkbHlcVjHiAhVSZWFkbHlcVjFcR1BCTWV0YWRhdGHqAgpSZWFkbHk6OlYxYgZwcm90bzM");

/**
 * Describes the message readly.v1.Date.
 * Use `create(DateSchema)` to create a new message.
 */
export const DateSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_date, 0);

