// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/reading_status.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file readly/v1/reading_status.proto.
 */
export const file_readly_v1_reading_status = /*@__PURE__*/
  fileDesc("Ch5yZWFkbHkvdjEvcmVhZGluZ19zdGF0dXMucHJvdG8SCXJlYWRseS52MSo/Cg1SZWFkaW5nU3RhdHVzEgoKBlVOUkVBRBAAEgsKB1JFQURJTkcQARIICgRET05FEAISCwoHVU5LTk9XThADQoABCg1jb20ucmVhZGx5LnYxQhJSZWFkaW5nU3RhdHVzUHJvdG9QAVoWcmVhZGx5L3BiL3JlYWRseS92MTtwYqICA1JYWKoCCVJlYWRseS5WMcoCCVJlYWRseVxWMeICFVJlYWRseVxWMVxHUEJNZXRhZGF0YeoCClJlYWRseTo6VjFiBnByb3RvMw");

/**
 * Describes the enum readly.v1.ReadingStatus.
 */
export const ReadingStatusSchema = /*@__PURE__*/
  enumDesc(file_readly_v1_reading_status, 0);

/**
 * @generated from enum readly.v1.ReadingStatus
 */
export const ReadingStatus = /*@__PURE__*/
  tsEnum(ReadingStatusSchema);

