// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_sign_up.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file readly/v1/rpc_sign_up.proto.
 */
export const file_readly_v1_rpc_sign_up = /*@__PURE__*/
  fileDesc("ChtyZWFkbHkvdjEvcnBjX3NpZ25fdXAucHJvdG8SCXJlYWRseS52MSI+Cg1TaWduVXBSZXF1ZXN0EgwKBG5hbWUYASABKAkSDQoFZW1haWwYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkiawoOU2lnblVwUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhUKDXJlZnJlc2hfdG9rZW4YAiABKAkSDwoHdXNlcl9pZBgDIAEoAxIMCgRuYW1lGAQgASgJEg0KBWVtYWlsGAUgASgJQnwKDWNvbS5yZWFkbHkudjFCDlJwY1NpZ25VcFByb3RvUAFaFnJlYWRseS9wYi9yZWFkbHkvdjE7cGKiAgNSWFiqAglSZWFkbHkuVjHKAglSZWFkbHlcVjHiAhVSZWFkbHlcVjFcR1BCTWV0YWRhdGHqAgpSZWFkbHk6OlYxYgZwcm90bzM");

/**
 * Describes the message readly.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_sign_up, 0);

/**
 * Describes the message readly.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_sign_up, 1);

