// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_refresh_token.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file readly/v1/rpc_refresh_token.proto.
 */
export declare const file_readly_v1_rpc_refresh_token: GenFile;

/**
 * @generated from message readly.v1.RefreshTokenRequest
 */
export declare type RefreshTokenRequest = Message<"readly.v1.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message readly.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export declare const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest>;

/**
 * @generated from message readly.v1.RefreshTokenResponse
 */
export declare type RefreshTokenResponse = Message<"readly.v1.RefreshTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message readly.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export declare const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse>;

