// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_sign_in.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file readly/v1/rpc_sign_in.proto.
 */
export const file_readly_v1_rpc_sign_in = /*@__PURE__*/
  fileDesc("ChtyZWFkbHkvdjEvcnBjX3NpZ25faW4ucHJvdG8SCXJlYWRseS52MSIwCg1TaWduSW5SZXF1ZXN0Eg0KBWVtYWlsGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJImsKDlNpZ25JblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEg8KB3VzZXJfaWQYAyABKAMSDAoEbmFtZRgEIAEoCRINCgVlbWFpbBgFIAEoCUJ8Cg1jb20ucmVhZGx5LnYxQg5ScGNTaWduSW5Qcm90b1ABWhZyZWFkbHkvcGIvcmVhZGx5L3YxO3BiogIDUlhYqgIJUmVhZGx5LlYxygIJUmVhZGx5XFYx4gIVUmVhZGx5XFYxXEdQQk1ldGFkYXRh6gIKUmVhZGx5OjpWMWIGcHJvdG8z");

/**
 * Describes the message readly.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_sign_in, 0);

/**
 * Describes the message readly.v1.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_sign_in, 1);

