// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_register_book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_readly_v1_date } from "./date_pb";
import { file_readly_v1_reading_status } from "./reading_status_pb";

/**
 * Describes the file readly/v1/rpc_register_book.proto.
 */
export const file_readly_v1_rpc_register_book = /*@__PURE__*/
  fileDesc("CiFyZWFkbHkvdjEvcnBjX3JlZ2lzdGVyX2Jvb2sucHJvdG8SCXJlYWRseS52MSL9AwoTUmVnaXN0ZXJCb29rUmVxdWVzdBINCgV0aXRsZRgBIAEoCRIOCgZnZW5yZXMYAiADKAkSGAoLZGVzY3JpcHRpb24YAyABKAlIAIgBARIcCg9jb3Zlcl9pbWFnZV91cmwYBCABKAlIAYgBARIQCgN1cmwYBSABKAlIAogBARIYCgthdXRob3JfbmFtZRgGIAEoCUgDiAEBEhsKDnB1Ymxpc2hlcl9uYW1lGAcgASgJSASIAQESKgoMcHVibGlzaF9kYXRlGAggASgLMg8ucmVhZGx5LnYxLkRhdGVIBYgBARIRCgRpc2JuGAkgASgJSAaIAQESMAoOcmVhZGluZ19zdGF0dXMYCiABKA4yGC5yZWFkbHkudjEuUmVhZGluZ1N0YXR1cxIoCgpzdGFydF9kYXRlGAsgASgLMg8ucmVhZGx5LnYxLkRhdGVIB4gBARImCghlbmRfZGF0ZRgMIAEoCzIPLnJlYWRseS52MS5EYXRlSAiIAQFCDgoMX2Rlc2NyaXB0aW9uQhIKEF9jb3Zlcl9pbWFnZV91cmxCBgoEX3VybEIOCgxfYXV0aG9yX25hbWVCEQoPX3B1Ymxpc2hlcl9uYW1lQg8KDV9wdWJsaXNoX2RhdGVCBwoFX2lzYm5CDQoLX3N0YXJ0X2RhdGVCCwoJX2VuZF9kYXRlQoIBCg1jb20ucmVhZGx5LnYxQhRScGNSZWdpc3RlckJvb2tQcm90b1ABWhZyZWFkbHkvcGIvcmVhZGx5L3YxO3BiogIDUlhYqgIJUmVhZGx5LlYxygIJUmVhZGx5XFYx4gIVUmVhZGx5XFYxXEdQQk1ldGFkYXRh6gIKUmVhZGx5OjpWMWIGcHJvdG8z", [file_readly_v1_date, file_readly_v1_reading_status]);

/**
 * Describes the message readly.v1.RegisterBookRequest.
 * Use `create(RegisterBookRequestSchema)` to create a new message.
 */
export const RegisterBookRequestSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_register_book, 0);

