// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_refresh_token.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file readly/v1/rpc_refresh_token.proto.
 */
export const file_readly_v1_rpc_refresh_token = /*@__PURE__*/
  fileDesc("CiFyZWFkbHkvdjEvcnBjX3JlZnJlc2hfdG9rZW4ucHJvdG8SCXJlYWRseS52MSIsChNSZWZyZXNoVG9rZW5SZXF1ZXN0EhUKDXJlZnJlc2hfdG9rZW4YASABKAkiLAoUUmVmcmVzaFRva2VuUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJQoIBCg1jb20ucmVhZGx5LnYxQhRScGNSZWZyZXNoVG9rZW5Qcm90b1ABWhZyZWFkbHkvcGIvcmVhZGx5L3YxO3BiogIDUlhYqgIJUmVhZGx5LlYxygIJUmVhZGx5XFYx4gIVUmVhZGx5XFYxXEdQQk1ldGFkYXRh6gIKUmVhZGx5OjpWMWIGcHJvdG8z");

/**
 * Describes the message readly.v1.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_refresh_token, 0);

/**
 * Describes the message readly.v1.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_refresh_token, 1);

