// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_delete_book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file readly/v1/rpc_delete_book.proto.
 */
export const file_readly_v1_rpc_delete_book = /*@__PURE__*/
  fileDesc("Ch9yZWFkbHkvdjEvcnBjX2RlbGV0ZV9ib29rLnByb3RvEglyZWFkbHkudjEiJAoRRGVsZXRlQm9va1JlcXVlc3QSDwoHYm9va19pZBgBIAEoA0KAAQoNY29tLnJlYWRseS52MUISUnBjRGVsZXRlQm9va1Byb3RvUAFaFnJlYWRseS9wYi9yZWFkbHkvdjE7cGKiAgNSWFiqAglSZWFkbHkuVjHKAglSZWFkbHlcVjHiAhVSZWFkbHlcVjFcR1BCTWV0YWRhdGHqAgpSZWFkbHk6OlYxYgZwcm90bzM");

/**
 * Describes the message readly.v1.DeleteBookRequest.
 * Use `create(DeleteBookRequestSchema)` to create a new message.
 */
export const DeleteBookRequestSchema = /*@__PURE__*/
  messageDesc(file_readly_v1_rpc_delete_book, 0);

