// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/rpc_delete_book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file readly/v1/rpc_delete_book.proto.
 */
export declare const file_readly_v1_rpc_delete_book: GenFile;

/**
 * @generated from message readly.v1.DeleteBookRequest
 */
export declare type DeleteBookRequest = Message<"readly.v1.DeleteBookRequest"> & {
  /**
   * @generated from field: int64 book_id = 1;
   */
  bookId: bigint;
};

/**
 * Describes the message readly.v1.DeleteBookRequest.
 * Use `create(DeleteBookRequestSchema)` to create a new message.
 */
export declare const DeleteBookRequestSchema: GenMessage<DeleteBookRequest>;

