// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/service_book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_readly_v1_book } from "./book_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_readly_v1_rpc_delete_book } from "./rpc_delete_book_pb";
import { file_readly_v1_rpc_register_book } from "./rpc_register_book_pb";

/**
 * Describes the file readly/v1/service_book.proto.
 */
export const file_readly_v1_service_book = /*@__PURE__*/
  fileDesc("ChxyZWFkbHkvdjEvc2VydmljZV9ib29rLnByb3RvEglyZWFkbHkudjEyxQEKC0Jvb2tTZXJ2aWNlElUKDFJlZ2lzdGVyQm9vaxIeLnJlYWRseS52MS5SZWdpc3RlckJvb2tSZXF1ZXN0Gg8ucmVhZGx5LnYxLkJvb2siFILT5JMCDjoBKiIJL3YxL2Jvb2tzEl8KCkRlbGV0ZUJvb2sSHC5yZWFkbHkudjEuRGVsZXRlQm9va1JlcXVlc3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiG4LT5JMCFSoTL3YxL2Jvb2tzL3tib29rX2lkfUJ+Cg1jb20ucmVhZGx5LnYxQhBTZXJ2aWNlQm9va1Byb3RvUAFaFnJlYWRseS9wYi9yZWFkbHkvdjE7cGKiAgNSWFiqAglSZWFkbHkuVjHKAglSZWFkbHlcVjHiAhVSZWFkbHlcVjFcR1BCTWV0YWRhdGHqAgpSZWFkbHk6OlYxYgZwcm90bzM", [file_readly_v1_book, file_google_api_annotations, file_google_protobuf_empty, file_readly_v1_rpc_delete_book, file_readly_v1_rpc_register_book]);

/**
 * @generated from service readly.v1.BookService
 */
export const BookService = /*@__PURE__*/
  serviceDesc(file_readly_v1_service_book, 0);

