// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/service_book.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { RegisterBookRequestSchema } from "./rpc_register_book_pb";
import type { BookSchema } from "./book_pb";
import type { DeleteBookRequestSchema } from "./rpc_delete_book_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file readly/v1/service_book.proto.
 */
export declare const file_readly_v1_service_book: GenFile;

/**
 * @generated from service readly.v1.BookService
 */
export declare const BookService: GenService<{
  /**
   * @generated from rpc readly.v1.BookService.RegisterBook
   */
  registerBook: {
    methodKind: "unary";
    input: typeof RegisterBookRequestSchema;
    output: typeof BookSchema;
  },
  /**
   * @generated from rpc readly.v1.BookService.DeleteBook
   */
  deleteBook: {
    methodKind: "unary";
    input: typeof DeleteBookRequestSchema;
    output: typeof EmptySchema;
  },
}>;

