// @generated by protoc-gen-es v2.2.5
// @generated from file readly/v1/service_user.proto (package readly.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_readly_v1_rpc_refresh_token } from "./rpc_refresh_token_pb";
import { file_readly_v1_rpc_sign_in } from "./rpc_sign_in_pb";
import { file_readly_v1_rpc_sign_up } from "./rpc_sign_up_pb";

/**
 * Describes the file readly/v1/service_user.proto.
 */
export const file_readly_v1_service_user = /*@__PURE__*/
  fileDesc("ChxyZWFkbHkvdjEvc2VydmljZV91c2VyLnByb3RvEglyZWFkbHkudjEyqAIKC1VzZXJTZXJ2aWNlElQKBlNpZ25JbhIYLnJlYWRseS52MS5TaWduSW5SZXF1ZXN0GhkucmVhZGx5LnYxLlNpZ25JblJlc3BvbnNlIhWC0+STAg86ASoiCi92MS9zaWduaW4SVAoGU2lnblVwEhgucmVhZGx5LnYxLlNpZ25VcFJlcXVlc3QaGS5yZWFkbHkudjEuU2lnblVwUmVzcG9uc2UiFYLT5JMCDzoBKiIKL3YxL3NpZ251cBJtCgxSZWZyZXNoVG9rZW4SHi5yZWFkbHkudjEuUmVmcmVzaFRva2VuUmVxdWVzdBofLnJlYWRseS52MS5SZWZyZXNoVG9rZW5SZXNwb25zZSIcgtPkkwIWOgEqIhEvdjEvcmVmcmVzaC10b2tlbkJ+Cg1jb20ucmVhZGx5LnYxQhBTZXJ2aWNlVXNlclByb3RvUAFaFnJlYWRseS9wYi9yZWFkbHkvdjE7cGKiAgNSWFiqAglSZWFkbHkuVjHKAglSZWFkbHlcVjHiAhVSZWFkbHlcVjFcR1BCTWV0YWRhdGHqAgpSZWFkbHk6OlYxYgZwcm90bzM", [file_google_api_annotations, file_readly_v1_rpc_refresh_token, file_readly_v1_rpc_sign_in, file_readly_v1_rpc_sign_up]);

/**
 * @generated from service readly.v1.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_readly_v1_service_user, 0);

