// @generated by protoc-gen-es v2.2.5
// @generated from file book.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { ReadingStatus } from "./reading_status_pb";

/**
 * Describes the file book.proto.
 */
export declare const file_book: GenFile;

/**
 * @generated from message pb.Book
 */
export declare type Book = Message<"pb.Book"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated string genres = 3;
   */
  genres: string[];

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional string cover_image_url = 5;
   */
  coverImageUrl?: string;

  /**
   * @generated from field: optional string url = 6;
   */
  url?: string;

  /**
   * @generated from field: optional string author_name = 7;
   */
  authorName?: string;

  /**
   * @generated from field: optional string publisher_name = 8;
   */
  publisherName?: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp publish_date = 9;
   */
  publishDate?: Timestamp;

  /**
   * @generated from field: optional string isbn = 10;
   */
  isbn?: string;

  /**
   * @generated from field: pb.ReadingStatus reading_status = 11;
   */
  readingStatus: ReadingStatus;

  /**
   * @generated from field: optional google.protobuf.Timestamp start_date = 12;
   */
  startDate?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp end_date = 13;
   */
  endDate?: Timestamp;
};

/**
 * Describes the message pb.Book.
 * Use `create(BookSchema)` to create a new message.
 */
export declare const BookSchema: GenMessage<Book>;

