// @generated by protoc-gen-es v2.2.5
// @generated from file book.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_reading_status } from "./reading_status_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file book.proto.
 */
export const file_book = /*@__PURE__*/
  fileDesc("Cgpib29rLnByb3RvEgJwYiKUBAoEQm9vaxIKCgJpZBgBIAEoAxINCgV0aXRsZRgCIAEoCRIOCgZnZW5yZXMYAyADKAkSGAoLZGVzY3JpcHRpb24YBCABKAlIAIgBARIcCg9jb3Zlcl9pbWFnZV91cmwYBSABKAlIAYgBARIQCgN1cmwYBiABKAlIAogBARIYCgthdXRob3JfbmFtZRgHIAEoCUgDiAEBEhsKDnB1Ymxpc2hlcl9uYW1lGAggASgJSASIAQESNQoMcHVibGlzaF9kYXRlGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgFiAEBEhEKBGlzYm4YCiABKAlIBogBARIpCg5yZWFkaW5nX3N0YXR1cxgLIAEoDjIRLnBiLlJlYWRpbmdTdGF0dXMSMwoKc3RhcnRfZGF0ZRgMIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIB4gBARIxCghlbmRfZGF0ZRgNIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBICIgBAUIOCgxfZGVzY3JpcHRpb25CEgoQX2NvdmVyX2ltYWdlX3VybEIGCgRfdXJsQg4KDF9hdXRob3JfbmFtZUIRCg9fcHVibGlzaGVyX25hbWVCDwoNX3B1Ymxpc2hfZGF0ZUIHCgVfaXNibkINCgtfc3RhcnRfZGF0ZUILCglfZW5kX2RhdGVCRgoGY29tLnBiQglCb29rUHJvdG9QAVoJcmVhZGx5L3BiogIDUFhYqgICUGLKAgJQYuICDlBiXEdQQk1ldGFkYXRh6gICUGJiBnByb3RvMw", [file_reading_status, file_google_protobuf_timestamp]);

/**
 * Describes the message pb.Book.
 * Use `create(BookSchema)` to create a new message.
 */
export const BookSchema = /*@__PURE__*/
  messageDesc(file_book, 0);

