// @generated by protoc-gen-es v2.2.5
// @generated from file date.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file date.proto.
 */
export declare const file_date: GenFile;

/**
 * @generated from message pb.Date
 */
export declare type Date = Message<"pb.Date"> & {
  /**
   * @generated from field: int32 year = 1;
   */
  year: number;

  /**
   * @generated from field: int32 month = 2;
   */
  month: number;

  /**
   * @generated from field: int32 day = 3;
   */
  day: number;
};

/**
 * Describes the message pb.Date.
 * Use `create(DateSchema)` to create a new message.
 */
export declare const DateSchema: GenMessage<Date>;

