// @generated by protoc-gen-es v2.2.5
// @generated from file date.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file date.proto.
 */
export const file_date = /*@__PURE__*/
  fileDesc("CgpkYXRlLnByb3RvEgJwYiIwCgREYXRlEgwKBHllYXIYASABKAUSDQoFbW9udGgYAiABKAUSCwoDZGF5GAMgASgFQkYKBmNvbS5wYkIJRGF0ZVByb3RvUAFaCXJlYWRseS9wYqICA1BYWKoCAlBiygICUGLiAg5QYlxHUEJNZXRhZGF0YeoCAlBiYgZwcm90bzM");

/**
 * Describes the message pb.Date.
 * Use `create(DateSchema)` to create a new message.
 */
export const DateSchema = /*@__PURE__*/
  messageDesc(file_date, 0);

