// @generated by protoc-gen-es v2.2.5
// @generated from file reading_status.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file reading_status.proto.
 */
export declare const file_reading_status: GenFile;

/**
 * @generated from enum pb.ReadingStatus
 */
export enum ReadingStatus {
  /**
   * @generated from enum value: UNREAD = 0;
   */
  UNREAD = 0,

  /**
   * @generated from enum value: READING = 1;
   */
  READING = 1,

  /**
   * @generated from enum value: DONE = 2;
   */
  DONE = 2,

  /**
   * @generated from enum value: UNKNOWN = 3;
   */
  UNKNOWN = 3,
}

/**
 * Describes the enum pb.ReadingStatus.
 */
export declare const ReadingStatusSchema: GenEnum<ReadingStatus>;

