// @generated by protoc-gen-es v2.2.5
// @generated from file reading_status.proto (package pb, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file reading_status.proto.
 */
export const file_reading_status = /*@__PURE__*/
  fileDesc("ChRyZWFkaW5nX3N0YXR1cy5wcm90bxICcGIqPwoNUmVhZGluZ1N0YXR1cxIKCgZVTlJFQUQQABILCgdSRUFESU5HEAESCAoERE9ORRACEgsKB1VOS05PV04QA0JPCgZjb20ucGJCElJlYWRpbmdTdGF0dXNQcm90b1ABWglyZWFkbHkvcGKiAgNQWFiqAgJQYsoCAlBi4gIOUGJcR1BCTWV0YWRhdGHqAgJQYmIGcHJvdG8z");

/**
 * Describes the enum pb.ReadingStatus.
 */
export const ReadingStatusSchema = /*@__PURE__*/
  enumDesc(file_reading_status, 0);

/**
 * @generated from enum pb.ReadingStatus
 */
export const ReadingStatus = /*@__PURE__*/
  tsEnum(ReadingStatusSchema);

