// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_refresh_token.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rpc_refresh_token.proto.
 */
export declare const file_rpc_refresh_token: GenFile;

/**
 * @generated from message pb.RefreshTokenRequest
 */
export declare type RefreshTokenRequest = Message<"pb.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message pb.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export declare const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest>;

/**
 * @generated from message pb.RefreshTokenResponse
 */
export declare type RefreshTokenResponse = Message<"pb.RefreshTokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message pb.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export declare const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse>;

