// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_delete_book.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file rpc_delete_book.proto.
 */
export const file_rpc_delete_book = /*@__PURE__*/
  fileDesc("ChVycGNfZGVsZXRlX2Jvb2sucHJvdG8SAnBiIiQKEURlbGV0ZUJvb2tSZXF1ZXN0Eg8KB2Jvb2tfaWQYASABKANCTwoGY29tLnBiQhJScGNEZWxldGVCb29rUHJvdG9QAVoJcmVhZGx5L3BiogIDUFhYqgICUGLKAgJQYuICDlBiXEdQQk1ldGFkYXRh6gICUGJiBnByb3RvMw");

/**
 * Describes the message pb.DeleteBookRequest.
 * Use `create(DeleteBookRequestSchema)` to create a new message.
 */
export const DeleteBookRequestSchema = /*@__PURE__*/
  messageDesc(file_rpc_delete_book, 0);

