// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_sign_up.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file rpc_sign_up.proto.
 */
export const file_rpc_sign_up = /*@__PURE__*/
  fileDesc("ChFycGNfc2lnbl91cC5wcm90bxICcGIiPgoNU2lnblVwUmVxdWVzdBIMCgRuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJImsKDlNpZ25VcFJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEg8KB3VzZXJfaWQYAyABKAMSDAoEbmFtZRgEIAEoCRINCgVlbWFpbBgFIAEoCUJLCgZjb20ucGJCDlJwY1NpZ25VcFByb3RvUAFaCXJlYWRseS9wYqICA1BYWKoCAlBiygICUGLiAg5QYlxHUEJNZXRhZGF0YeoCAlBiYgZwcm90bzM");

/**
 * Describes the message pb.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema = /*@__PURE__*/
  messageDesc(file_rpc_sign_up, 0);

/**
 * Describes the message pb.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema = /*@__PURE__*/
  messageDesc(file_rpc_sign_up, 1);

