// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_refresh_token.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file rpc_refresh_token.proto.
 */
export const file_rpc_refresh_token = /*@__PURE__*/
  fileDesc("ChdycGNfcmVmcmVzaF90b2tlbi5wcm90bxICcGIiLAoTUmVmcmVzaFRva2VuUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJIiwKFFJlZnJlc2hUb2tlblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCUJRCgZjb20ucGJCFFJwY1JlZnJlc2hUb2tlblByb3RvUAFaCXJlYWRseS9wYqICA1BYWKoCAlBiygICUGLiAg5QYlxHUEJNZXRhZGF0YeoCAlBiYgZwcm90bzM");

/**
 * Describes the message pb.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema = /*@__PURE__*/
  messageDesc(file_rpc_refresh_token, 0);

/**
 * Describes the message pb.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema = /*@__PURE__*/
  messageDesc(file_rpc_refresh_token, 1);

