// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_register_book.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_date } from "./date_pb";
import { file_reading_status } from "./reading_status_pb";

/**
 * Describes the file rpc_register_book.proto.
 */
export const file_rpc_register_book = /*@__PURE__*/
  fileDesc("ChdycGNfcmVnaXN0ZXJfYm9vay5wcm90bxICcGIi4QMKE1JlZ2lzdGVyQm9va1JlcXVlc3QSDQoFdGl0bGUYASABKAkSDgoGZ2VucmVzGAIgAygJEhgKC2Rlc2NyaXB0aW9uGAMgASgJSACIAQESHAoPY292ZXJfaW1hZ2VfdXJsGAQgASgJSAGIAQESEAoDdXJsGAUgASgJSAKIAQESGAoLYXV0aG9yX25hbWUYBiABKAlIA4gBARIbCg5wdWJsaXNoZXJfbmFtZRgHIAEoCUgEiAEBEiMKDHB1Ymxpc2hfZGF0ZRgIIAEoCzIILnBiLkRhdGVIBYgBARIRCgRpc2JuGAkgASgJSAaIAQESKQoOcmVhZGluZ19zdGF0dXMYCiABKA4yES5wYi5SZWFkaW5nU3RhdHVzEiEKCnN0YXJ0X2RhdGUYCyABKAsyCC5wYi5EYXRlSAeIAQESHwoIZW5kX2RhdGUYDCABKAsyCC5wYi5EYXRlSAiIAQFCDgoMX2Rlc2NyaXB0aW9uQhIKEF9jb3Zlcl9pbWFnZV91cmxCBgoEX3VybEIOCgxfYXV0aG9yX25hbWVCEQoPX3B1Ymxpc2hlcl9uYW1lQg8KDV9wdWJsaXNoX2RhdGVCBwoFX2lzYm5CDQoLX3N0YXJ0X2RhdGVCCwoJX2VuZF9kYXRlQlEKBmNvbS5wYkIUUnBjUmVnaXN0ZXJCb29rUHJvdG9QAVoJcmVhZGx5L3BiogIDUFhYqgICUGLKAgJQYuICDlBiXEdQQk1ldGFkYXRh6gICUGJiBnByb3RvMw", [file_date, file_reading_status]);

/**
 * Describes the message pb.RegisterBookRequest.
 * Use `create(RegisterBookRequestSchema)` to create a new message.
 */
export const RegisterBookRequestSchema = /*@__PURE__*/
  messageDesc(file_rpc_register_book, 0);

