// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_sign_in.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file rpc_sign_in.proto.
 */
export const file_rpc_sign_in = /*@__PURE__*/
  fileDesc("ChFycGNfc2lnbl9pbi5wcm90bxICcGIiMAoNU2lnbkluUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSJrCg5TaWduSW5SZXNwb25zZRIUCgxhY2Nlc3NfdG9rZW4YASABKAkSFQoNcmVmcmVzaF90b2tlbhgCIAEoCRIPCgd1c2VyX2lkGAMgASgDEgwKBG5hbWUYBCABKAkSDQoFZW1haWwYBSABKAlCSwoGY29tLnBiQg5ScGNTaWduSW5Qcm90b1ABWglyZWFkbHkvcGKiAgNQWFiqAgJQYsoCAlBi4gIOUGJcR1BCTWV0YWRhdGHqAgJQYmIGcHJvdG8z");

/**
 * Describes the message pb.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema = /*@__PURE__*/
  messageDesc(file_rpc_sign_in, 0);

/**
 * Describes the message pb.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema = /*@__PURE__*/
  messageDesc(file_rpc_sign_in, 1);

