// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_delete_book.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file rpc_delete_book.proto.
 */
export declare const file_rpc_delete_book: GenFile;

/**
 * @generated from message pb.DeleteBookRequest
 */
export declare type DeleteBookRequest = Message<"pb.DeleteBookRequest"> & {
  /**
   * @generated from field: int64 book_id = 1;
   */
  bookId: bigint;
};

/**
 * Describes the message pb.DeleteBookRequest.
 * Use `create(DeleteBookRequestSchema)` to create a new message.
 */
export declare const DeleteBookRequestSchema: GenMessage<DeleteBookRequest>;

