// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_register_book.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_reading_status } from "./reading_status_pb";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file rpc_register_book.proto.
 */
export const file_rpc_register_book = /*@__PURE__*/
  fileDesc("ChdycGNfcmVnaXN0ZXJfYm9vay5wcm90bxICcGIilwQKE1JlZ2lzdGVyQm9va1JlcXVlc3QSDQoFdGl0bGUYASABKAkSDgoGZ2VucmVzGAIgAygJEhgKC2Rlc2NyaXB0aW9uGAMgASgJSACIAQESHAoPY292ZXJfaW1hZ2VfdXJsGAQgASgJSAGIAQESEAoDdXJsGAUgASgJSAKIAQESGAoLYXV0aG9yX25hbWUYBiABKAlIA4gBARIbCg5wdWJsaXNoZXJfbmFtZRgHIAEoCUgEiAEBEjUKDHB1Ymxpc2hfZGF0ZRgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIBYgBARIRCgRpc2JuGAkgASgJSAaIAQESKQoOcmVhZGluZ19zdGF0dXMYCiABKA4yES5wYi5SZWFkaW5nU3RhdHVzEjMKCnN0YXJ0X2RhdGUYCyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAeIAQESMQoIZW5kX2RhdGUYDCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAiIAQFCDgoMX2Rlc2NyaXB0aW9uQhIKEF9jb3Zlcl9pbWFnZV91cmxCBgoEX3VybEIOCgxfYXV0aG9yX25hbWVCEQoPX3B1Ymxpc2hlcl9uYW1lQg8KDV9wdWJsaXNoX2RhdGVCBwoFX2lzYm5CDQoLX3N0YXJ0X2RhdGVCCwoJX2VuZF9kYXRlQlEKBmNvbS5wYkIUUnBjUmVnaXN0ZXJCb29rUHJvdG9QAVoJcmVhZGx5L3BiogIDUFhYqgICUGLKAgJQYuICDlBiXEdQQk1ldGFkYXRh6gICUGJiBnByb3RvMw", [file_reading_status, file_google_protobuf_timestamp]);

/**
 * Describes the message pb.RegisterBookRequest.
 * Use `create(RegisterBookRequestSchema)` to create a new message.
 */
export const RegisterBookRequestSchema = /*@__PURE__*/
  messageDesc(file_rpc_register_book, 0);

