// @generated by protoc-gen-es v2.2.5
// @generated from file rpc_register_book.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "./date_pb";
import type { ReadingStatus } from "./reading_status_pb";

/**
 * Describes the file rpc_register_book.proto.
 */
export declare const file_rpc_register_book: GenFile;

/**
 * @generated from message pb.RegisterBookRequest
 */
export declare type RegisterBookRequest = Message<"pb.RegisterBookRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: repeated string genres = 2;
   */
  genres: string[];

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: optional string cover_image_url = 4;
   */
  coverImageUrl?: string;

  /**
   * @generated from field: optional string url = 5;
   */
  url?: string;

  /**
   * @generated from field: optional string author_name = 6;
   */
  authorName?: string;

  /**
   * @generated from field: optional string publisher_name = 7;
   */
  publisherName?: string;

  /**
   * @generated from field: optional pb.Date publish_date = 8;
   */
  publishDate?: Date;

  /**
   * @generated from field: optional string isbn = 9;
   */
  isbn?: string;

  /**
   * @generated from field: pb.ReadingStatus reading_status = 10;
   */
  readingStatus: ReadingStatus;

  /**
   * @generated from field: optional pb.Date start_date = 11;
   */
  startDate?: Date;

  /**
   * @generated from field: optional pb.Date end_date = 12;
   */
  endDate?: Date;
};

/**
 * Describes the message pb.RegisterBookRequest.
 * Use `create(RegisterBookRequestSchema)` to create a new message.
 */
export declare const RegisterBookRequestSchema: GenMessage<RegisterBookRequest>;

