// @generated by protoc-gen-es v2.2.5
// @generated from file service_user.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "./google/api/annotations_pb";
import { file_rpc_refresh_token } from "./rpc_refresh_token_pb";
import { file_rpc_sign_in } from "./rpc_sign_in_pb";
import { file_rpc_sign_up } from "./rpc_sign_up_pb";

/**
 * Describes the file service_user.proto.
 */
export const file_service_user = /*@__PURE__*/
  fileDesc("ChJzZXJ2aWNlX3VzZXIucHJvdG8SAnBiMv4BCgtVc2VyU2VydmljZRJGCgZTaWduSW4SES5wYi5TaWduSW5SZXF1ZXN0GhIucGIuU2lnbkluUmVzcG9uc2UiFYLT5JMCDzoBKiIKL3YxL3NpZ25pbhJGCgZTaWduVXASES5wYi5TaWduVXBSZXF1ZXN0GhIucGIuU2lnblVwUmVzcG9uc2UiFYLT5JMCDzoBKiIKL3YxL3NpZ251cBJfCgxSZWZyZXNoVG9rZW4SFy5wYi5SZWZyZXNoVG9rZW5SZXF1ZXN0GhgucGIuUmVmcmVzaFRva2VuUmVzcG9uc2UiHILT5JMCFjoBKiIRL3YxL3JlZnJlc2gtdG9rZW5CTQoGY29tLnBiQhBTZXJ2aWNlVXNlclByb3RvUAFaCXJlYWRseS9wYqICA1BYWKoCAlBiygICUGLiAg5QYlxHUEJNZXRhZGF0YeoCAlBiYgZwcm90bzM", [file_google_api_annotations, file_rpc_refresh_token, file_rpc_sign_in, file_rpc_sign_up]);

/**
 * @generated from service pb.UserService
 */
export const UserService = /*@__PURE__*/
  serviceDesc(file_service_user, 0);

