// @generated by protoc-gen-es v2.2.5
// @generated from file service_book.proto (package pb, syntax proto3)
/* eslint-disable */

import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_book } from "./book_pb";
import { file_google_api_annotations } from "./google/api/annotations_pb";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import { file_rpc_delete_book } from "./rpc_delete_book_pb";
import { file_rpc_register_book } from "./rpc_register_book_pb";

/**
 * Describes the file service_book.proto.
 */
export const file_service_book = /*@__PURE__*/
  fileDesc("ChJzZXJ2aWNlX2Jvb2sucHJvdG8SAnBiMrABCgtCb29rU2VydmljZRJHCgxSZWdpc3RlckJvb2sSFy5wYi5SZWdpc3RlckJvb2tSZXF1ZXN0GggucGIuQm9vayIUgtPkkwIOOgEqIgkvdjEvYm9va3MSWAoKRGVsZXRlQm9vaxIVLnBiLkRlbGV0ZUJvb2tSZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IhuC0+STAhUqEy92MS9ib29rcy97Ym9va19pZH1CTQoGY29tLnBiQhBTZXJ2aWNlQm9va1Byb3RvUAFaCXJlYWRseS9wYqICA1BYWKoCAlBiygICUGLiAg5QYlxHUEJNZXRhZGF0YeoCAlBiYgZwcm90bzM", [file_book, file_google_api_annotations, file_google_protobuf_empty, file_rpc_delete_book, file_rpc_register_book]);

/**
 * @generated from service pb.BookService
 */
export const BookService = /*@__PURE__*/
  serviceDesc(file_service_book, 0);

