// @generated by protoc-gen-es v2.2.5
// @generated from file service_user.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { SignInRequestSchema, SignInResponseSchema } from "./rpc_sign_in_pb";
import type { SignUpRequestSchema, SignUpResponseSchema } from "./rpc_sign_up_pb";
import type { RefreshTokenRequestSchema, RefreshTokenResponseSchema } from "./rpc_refresh_token_pb";

/**
 * Describes the file service_user.proto.
 */
export declare const file_service_user: GenFile;

/**
 * @generated from service pb.UserService
 */
export declare const UserService: GenService<{
  /**
   * @generated from rpc pb.UserService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof SignInResponseSchema;
  },
  /**
   * @generated from rpc pb.UserService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof SignUpResponseSchema;
  },
  /**
   * @generated from rpc pb.UserService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
}>;

