name: Compare main branch with latest commit storybook component

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare:
    name: Compare main branch with latest commit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build storybook
        run: npm run build-storybook

      - name: Capture latest screenshots
        run: npm run capture-actual

      - name: Get latest capture all workflow run id
        id: get_run_id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=$(gh run list --branch main --workflow capture-all-stories.yml --limit 1 --json databaseId | jq ".[].databaseId")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Download base screenshots
        uses: actions/download-artifact@v4
        with:
          # https://github.com/actions/download-artifact
          # 別ワークフローからアーティファクトを取得するにはname, github-token: , repository, run-idは必須
          name: base-screenshots
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get_run_id.outputs.RUN_ID }}
          path: __screenshots__/__base__

      - name: Compare screenshots by reg-cli
        run: |
          npm run diff-screenshot

      - name: Upload diff screenshots
        # 差分検出されると前のstepが失敗するが差分をアップロードして欲しいのでalways指定
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diff-screenshots
          path: __screenshots__/__diff__
          retention-days: 5

